//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModUpdater {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Lang : global::System.Configuration.ApplicationSettingsBase {
        
        private static Lang defaultInstance = ((Lang)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Lang())));
        
        public static Lang Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to seaboy1234\'s {0} version {1}.")]
        public string WelcomeStr {
            get {
                return ((string)(this["WelcomeStr"]));
            }
            set {
                this["WelcomeStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There are {0} mods that need updating.")]
        public string NewModsStr {
            get {
                return ((string)(this["NewModsStr"]));
            }
            set {
                this["NewModsStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There are no updates.")]
        public string NoNewMods {
            get {
                return ((string)(this["NoNewMods"]));
            }
            set {
                this["NoNewMods"] = value;
            }
        }
    }
}
